apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-ingress
  labels:
    name: booking-ingress
spec:
  ingressClassName: kong
  rules:
  - host: ~APP_HOST
    http:
      paths:
      - pathType: Prefix
        path: "/auth"
        backend:
          service:
            name: keycloak
            port:
              number: 8080
