apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-guarded-ingress
  labels:
    name: booking-guarded-ingress
  annotations:
    konghq.com/plugins: api-gateway
spec:
  ingressClassName: kong
  rules:
  - host: ~APP_HOST
    http:
      paths:
      - pathType: Prefix
        path: "/api/customers"
        backend:
          service:
            name: customers-service
            port:
              number: 3000
      - pathType: Prefix
        path: "/api/orders"
        backend:
          service:
            name: orders-service
            port:
              number: 3000
