apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: api-gateway
config:
  minute: "10"
  super_admin:
    - "res:user":
        - "scopes:view"
    - "res:policy":
         - "scopes:edit"
plugin: api-gateway
